### ISSUE TITLE
-a and -A

### ISSUE THREAD

**Issue by Wingysam** [autofitcloud/lsvine#2]
Thanks for making lsvine! This is very useful!

I can't seem to display hidden files. It gives me the help file when I try `-a` or `-A`. When I try `lsvine --help` it doesn't display any options except for the path to view.

Could an option to display hidden files be added?

Thanks!

**Comment by shadiakiki1986** [comment]
> Could an option to display hidden files be added?

You bet :) Just released a new version with the `-a` option. Upgrade `lsvine` to 0.2.5

**Comment by Wingysam** [comment]
Thanks!
